---
title: Guía Docente
bibliography: assets/references/refs_guiadocente.bib
csl: assets/references/ecology.csl
nocite: |
  @*
---

Enlace a la [Guía Docente Oficial]((https://masteres.ugr.es/sites/master/default/public/guias-firmadas/2023/M64-56-2-22.pdf)) aprobada para el curso 2024-2025. 

## Breve descripción de contenidos 

Esta materia organiza sus contenidos en torno al concepto de ciclo de gestión del dato [@MichenerJones2012EcoinformaticsSupporting]. Se trata de mejorar la capacidad de los estudiantes para manejar la información desde que es capturada en campo hasta que es utilizada por gestores, científicos o el público en general. Se abordarán varias fases: captura de datos (diseño experimental, fotointerpretación), almacenamiento de información (metadatos y bases de datos geográficas), análisis de datos (análisis estadístico y modelización de procesos) y divulgación de contenidos (web, portales de datos, reproducibilidad, etc.). En cada una de las fases anteriores se adquirirán competencias relacionadas con el manejo de información ecológica: programación, bases de datos relacionales, teledetección, técnicas de reproducibilidad, acceso a datos primarios de biodiversidad, etc.

La metodología docente de la asignatura se basa en el aprendizaje basado en proyectos. Se plantearán a los estudiantes preguntas relacionadas con la gestión de recursos naturales. Para responder esas preguntas se requieren habilidades de investigación y también conocimiento sobre gestión de recursos. En el proceso de realizar este proyecto (y por tanto de responder a una pregunta en concreto), los estudiantes irán adquiriendo una serie de competencias relacionadas con los aspectos mostrados anteriormente del ciclo de gestión del dato.

## Prerrequisitos y/o Recomendaciones 
Es altamente recomendable que los alumnos matriculados tengan un conocimiento medio-alto de informática, o gran interés por adquirirlo. Deberán entender la estructura del sistema operativo Windows, Mac o Linux, moverse bien por las carpetas, instalar aplicaciones, etc.

## Resultados de aprendizaje (Objetivos)
***El alumno sabrá/comprenderá:***

- La importancia del manejo de la información ambiental y de la biodiversidad para su desempeño profesional.
- Deberá entender los distintos pasos que hay que dar para obtener conocimiento útil a partir de los datos originales tomados en el campo.
- También comprenderá el concepto de big data y la necesidad de contar con herramientas avanzadas para manejar grandes volúmenes de información. La componente espacial de la información ambiental, así como la temporal también serán conceptos clave en esta asignatura.

***El alumno será capaz de:***

- Identificar los distintos pasos del ciclo de gestión del dato de manera específica para cualquier problema relacionado con la biología de la conservación en la que haya información ambiental implicada.
- Diseñar una base de datos relacional para almacenar datos a partir de un diseño experimental dado.
- Documentar los datos tomados mediante distintos estándares existentes.
- Consultar y descargar datos especializados de distintos portales específicos relacionados con biología de la conservación.
- Manejar, procesar y analizar información geoespacial. 
- Aplicar técnicas de análisis de datos relacionados con la gestión y estudio de la biodiversidad en un contexto de cambio global (por ejemplo series temporales, etc). 
- Comprender elementos básicos de teledetección, así como utilizar productos disponibles online.
- Entender e implementar elementos básicos de programación útiles para desarrollar su actividad profesional (bucles, iteración de procesos, conexión con bases de datos, etc.).
- Aplicar metodologías y aproximaciones que permitan tener un flujo de trabajo reproducible, así como usar repositorios para almacenar y compartir flujos de trabajo y código ([GitHub](https://github.com/), [GitLab](https://gitlab.com/)). 

## Programa de contenidos teóricos y prácticos
### Teórico

Debido al carácter eminentemente práctico de la asignatura, no resulta del todo útil describirla siguiendo el clásico esquema de temas. No obstante, se presentan a continuación una serie de elementos teórico-prácticos que serán impartidos en la asignatura. El orden descrito aquí es flexible y dependerá de la configuración de la clase y de otros factores.

- Presentación de la asignatura. Generalidades sobre la ecoinformática. Necesidad de habilidades para manejar información. Concepto de flujo de trabajo como herramienta para planificar el abordaje de problemas.
- Reproducibilidad en ciencia. Generalidades sobre reproducibilidad en ciencia. Uso de herramientas para facilitar que nuestro trabajo sea reproducible, por otros y por nosotros mismos. Creación de documentos reproducibles. Control de versiones. 
- Introducción a la programación (nociones de [R](https://www.r-project.org/)).
- Captura y Almacenamiento de información. Identificación de las fuentes de datos necesarias para abordar el problema seleccionado. 
- Herramientas para almacenar y representar información geoespacial: Bases de datos relacionales. Sistemas de Información geográfica. 
- Fuentes de información disponibles. Portales integrados de acceso a información ambiental y datos sobre biodiversidad.
- Procesamiento/integración de información y análisis de resultados: análisis de series temporales, evaluación multicriterio, álgebra de mapas, etc.
- Teledetección: Aspectos generales. Series temporales. Variables ambientales relevantes. Introducción a [Google Earth Engine](https://earthengine.google.com/). 
- Datos primarios de biodiversidad e integración de datos en repositorios. Repositorios de información sobre biodiversidad. Se analizarán los principales repositorios existentes para almacenar datos sobre biodiversidad. También se estudiará el concepto de datapaper como herramienta básica para documentar y poner a disposición de la sociedad los datos científicos.

### Práctico
La asignatura combina los contenidos teóricos con los prácticos. Usamos la técnica docente de "aprendizaje basado en proyectos". Esto implica que los alumnos aprenden una serie de contenidos teóricos a partir de su aplicación a problemas reales. Durante la asignatura trataremos diversos temas y trabajaremos con herramientas que nos permitirán abordar una problemática relacionada con la toma de decisiones en la gestión del medio natural. La problemática o el proyecto concreto a abordar estará abierto a los intereses del alumnado. El planteamiento del proyecto se presentará al resto del grupo, momento en el que se darán pautas y recomendaciones para su ejecución y presentación final.

## Evaluación (instrumentos de evaluación, criterios de evaluación y porcentaje sobre la calificación final)
### Evaluación ordinaria

El artículo 17 de la Normativa de Evaluación y Calificación de los Estudiantes de la Universidad de Granada establece que la convocatoria ordinaria estará basada preferentemente en la evaluación continua del estudiante, excepto para quienes se le haya reconocido el derecho a la evaluación única final.

En esta asignatura se promueve la evaluación continua y se usan los siguientes instrumentos (descritos en el documento VERIFICA)

- Actividades de evaluación continua. Durante el desarrollo de la asignatura se realizan actividades calificables que permiten poner en práctica lo aprendido durante las clases. Deben de completarlas cada semana o cada dos semanas. Estas actividades suponen un 30% de la calificación final y corresponden con los siguientes instrumentos de evaluación de VERIFICA:

  - Pruebas, ejercicios y problemas, resueltos en clase o individualmente a lo largo del curso.
  - Memorias

- Trabajo final realizado en grupo o de forma individual para cuya realización es necesario poner en práctica buena parte de las competencias adquiridas durante la asignatura. Se trata de un trabajo sintético que tiene un valor en la calificación final del 60%. Corresponde con las siguientes actividades de VERIFICA:
  
  - Valoración final de informes, trabajos, proyectos, etc.
  - Memorias.
  - Pruebas escritas.

- Participación en clase. Con este instrumento se pretende evaluar la implicación del estudiante en la asignatura. Tiene un peso del 10% de la calificación final. Corresponde con los siguientes instrumentos del documento VERIFICA del máster:

  - Presentaciones orales.
  - Aportaciones del estudiante en sesiones de discusión y actitud del estudiante en las diferentes actividades desarrolladas.

### Evaluación extraordinaria
El artículo 19 de la Normativa de Evaluación y Calificación de los Estudiantes de la Universidad de Granada establece que los estudiantes que no hayan superado la asignatura en la convocatoria ordinaria dispondrán de una convocatoria extraordinaria. A ella podrán concurrir todos los estudiantes, con independencia de haber seguido o no un proceso de evaluación continua. De esta forma, el estudiante que no haya realizado la evaluación continua tendrá la posibilidad de obtener el 100% de la calificación mediante la realización de un trabajo o examen individual. En dicho examen se evaluarán las competencias propias de la asignatura. Aquellos estudiantes que hayan fallado en alguna de las pruebas descritas anteriormente, deberán repetirlas y volver a entregarlas dentro los plazos previamente acordados con los profesores.

### Evaluación única final
El artículo 8 de la Normativa de Evaluación y Calificación de los Estudiantes de la Universidad de Granada establece que podrán acogerse a la evaluación única final, el estudiante que no pueda cumplir con el método de evaluación continua por causas justificadas.
Para acogerse a la evaluación única final, el estudiante, en las dos primeras semanas de impartición de la asignatura o en las dos semanas siguientes a su matriculación si ésta se ha producido con posterioridad al inicio de las clases, lo solicitará, a través del procedimiento electrónico, a la Coordinación del Máster, quien dará traslado al profesorado correspondiente, alegando y acreditando las razones que le asisten para no poder seguir el sistema de evaluación continua.

La evaluación en tal caso consistirá en:

- Realización de un trabajo de tema libre que esté relacionado con el objeto de la asignatura. El tema del trabajo será consensuado con los profesores, que orientarán a los estudiantes en el proceso de elaboración del mismo. Este trabajo supondrá el 50% de la nota final.
- Examen práctico que contendrá ejercicios de manejo de información y análisis de datos relacionados con los contenidos de la asignatura. El estudiante deberá completarlos usando su ordenador o uno dispuesto por la UGR. Este examen supondrá el 50% de la calificación final.

## Información adicional
La asignatura de ***Ciclo de Gestión de los datos: Ecoinformática*** está coordinada con las asignaturas de [Funciones y Servicios de los Ecosistemas (FySE)](https://masteres.ugr.es/sites/master/default/public/guias-firmadas/2023/M64-56-2-23.pdf) y  [Diseño y Gestión de Áreas Protegidas (DyGAP)](https://masteres.ugr.es/sites/master/default/public/guias-firmadas/2023/M64-56-2-24.pdf), dentro de las posibles narrativas transversales podrían estar las siguientes:

- ***Gestión adaptativa para la naturalización de pinares***

  - Se mostrarán algunos de los problemas que pueden presentar las masas de pinares monoespecíficas, coetáneas y muy densas: decaimiento, baja resiliencia, y empobrecimiento. 
  - Se reflexionará sobre la necesidad de promover acciones de adaptación de los pinares para potenciar su papel como espacios protectores del bienestar humano frente al cambio global.
  - Identificación mediante SIG y teledetección de rodales que estén sufriendo decaimiento y sobre los que deberían realizarse actuaciones para aumentar su resiliencia y biodiversidad.
  - Principios de la gestión adaptativa y análisis de resultados obtenidos en las prácticas de Ecoinformática para incorporar los criterios de gestión de masas forestales en los planes de gestión de las áreas protegidas para hacerlas más biodiversas y resilientes.
  
- ***Incorporación de la perspectiva de funciones y servicios de los ecosistemas en el diseño y gestión de áreas protegidas promoviendo la interfaz ciencia-gestión-sociedad***.
  
  - Potencialidades que tiene la perspectiva de funciones y servicios de los ecosistemas y de la interfaz ciencia-gestión-sociedad para el diseño y gestión de áreas protegidas.
  - Caracterización de la diversidad funcional a nivel de ecosistema mediante teledetección (e.g., https://obsnev.es/apps/efts_SN.html).
  - Se incorporarán a los criterios biofísicos centrados en especies y hábitats, los criterios de riqueza y rareza de ecosistemas funcionales para la identificación de huecos en la Red Natura 2000. Se evaluará el grado de complementariedad y redundancia entre las prioridades basadas en hábitats y especies, y basadas en funciones y servicios de los ecosistemas.
  
NOTA: Es aconsejable cursar las tres asignaturas, aunque no es imprescindible.

## Software Libre usado:
- [R](https://www.r-project.org/) 
- [RStudio](https://posit.co/download/rstudio-desktop/)
- [QGIS](https://www.qgis.org/)
- [Git](https://git-scm.com/)

## Enlaces recomendados
- https://aprendiendo-r-intro.netlify.app/que-es-r   
- https://ajpelu.github.io/diveRpine/     
- The Turing Way handbook to reproducible, ethical and collaborative data science.
- https://book.the-turing-way.org/index.html 

## Bibliografía Recomendada
