---
title: "Práctica Documentos Reproducibles"
author: 
  - name: "[Antonio J. Pérez-Luque](equipo/perez_luque)"
    orcid: 0000-0002-1747-0469
    email: antonio.perez@inia.csic.es
    affiliation: Instituto de Ciencias Forestales (CIFOR) | INIA-CSIC (Madrid)
date: 2025-01-09
modulo: Reproducibilidad
practica: 1
format: html
number-sections: true
number-depth: 4
crossref:
  fig-title: Figura     # (default is "Figure")
  tbl-title: Tabla     # (default is "Table")
  title-delim: .     # (default is ":")
  fig-prefix: Figura
  tbl-prefix: Tabla
  ref-hyperlink: true
  sec-prefix: ""
  sec-labels: alpha
---

# Introducción {.unnumbered}

# Objetivos

-   Aprender a crear documentos `.Rmd` que combinan código con texto narrativo

# Actividades

-   Elige un conjunto de datos sobre el que quieras realizar el documento reproducible.

-   Genera un documento reproducible que contenga diferentes elementos

    -   **nivel básico**:
        -   Una imagen
        -   Texto en negrita, cursiva
        -   Enlaces a diferentes webs
        -   Un trozo de código
        -   Un gráfico generado a partir de un trozo de código (el alumno tiene que importar el archivo de datos)
    -   **nivel medio**:
        -   una tabla procesada a partir de un código
        -   Referencias bibliográficas
    -   **nivel experto**:
        -   elementos interactivos (*e.g.* mapa)

## Entrega

::: {.callout-important}
# Material a entregar
Cada alumno debe entregar una carpeta (en formato comprimido `.zip`) que contenga al menos los siguientes ficheros: el archivo `.Rmd`; el archivo de salida generado (`word`, `pdf`), el conjunto datos usado, y el resto de archivos necesarios para renderizar el documento (*e.g.* imágenes, etc.)
::: 

## Recursos

Para la realización de este ejercicio práctico consulta las diapositivas y el temario que se ha dado en clase así como algunos de los recursos incluidos, como por ejemplo:

-   [R for Data Science](https://es.r4ds.hadley.nz/r-markdown.html) en especial los capítulos 27 a 29 en su versión en castellano.

-   [R for Reproducible Scientific Analysis (RMarkdown / knitr)](https://reproducible-analysis-workshop.readthedocs.io/en/latest/6.RMarkdown-knitr.html)

-   [Reproducible reports with R markdown](https://intro2r.com/rmarkdown_r.html)

-   [R para Análisis Científicos Reproducibles](https://swcarpentry.github.io/r-novice-gapminder-es/15-knitr-markdown/index.html)

-   [Level up in R Markdown](https://allisonhorst.github.io/ucsb-qmss-rmarkdown/)

-   [Introducing RStudio and R Markdown](https://www.pipinghotdata.com/posts/2020-09-07-introducing-the-rstudio-ide-and-r-markdown/)

-   [Curso de Introducción a R](https://www.uv.es/vcoll/RMarkdown.html)

-   [Escribir un Trabajo Fin de Estudios con R Markdown](http://destio.us.es/calvo/memoriatfe/MemoriaTFE_PedroLuque_2017Nov_imprimir2caras.pdf)

-   ... Existen muchos más
